// LOCALHOST
GET http://localhost/8080/pillows
###
GET http://localhost/8080/pillows/6468e61237e6da8ae00dffed
###
POST http://localhost/8080/pillows
###
PUT http://localhost/8080/pillows/6468e61237e6da8ae00dffed
###
DELETE http://localhost/8080/pillows/6468e61237e6da8ae00dffed
###
GET http://localhost/8080/users
###
GET http://localhost/8080/users/6468e66637e6da8ae00dfff0
###
POST http://localhost/8080/users
###
PUT http://localhost/8080/users/6468e66637e6da8ae00dfff0
###
DELETE http://localhost/8080/users/6468e66637e6da8ae00dfff0

// PRODUCTION
GET https://cse341-lesson08-project.onrender.com/pillows
###
GET https://cse341-lesson08-project.onrender.com/pillows/6468e61237e6da8ae00dffed
###
POST https://cse341-lesson08-project.onrender.com/pillows
###
PUT https://cse341-lesson08-project.onrender.com/pillows/6468e61237e6da8ae00dffed
###
DELETE https://cse341-lesson08-project.onrender.com/pillows/6468e61237e6da8ae00dffed
###
GET https://cse341-lesson08-project.onrender.com/users
###
GET https://cse341-lesson08-project.onrender.com/users/6468e66637e6da8ae00dfff0
###
POST https://cse341-lesson08-project.onrender.com/users
###
PUT https://cse341-lesson08-project.onrender.com/users/6468e66637e6da8ae00dfff0
###
DELETE https://cse341-lesson08-project.onrender.com/users/6468e66637e6da8ae00dfff0